# Generated by Django 5.1.2 on 2025-10-24 05:12

import django.contrib.postgres.fields
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LearningPathway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pathway_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('tenant', models.CharField(db_index=True, max_length=100)),
                ('student_id', models.CharField(db_index=True, max_length=100)),
                ('student_name', models.CharField(max_length=200)),
                ('pathway_name', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('difficulty_level', models.CharField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced'), ('expert', 'Expert')], default='beginner', max_length=20)),
                ('estimated_duration_hours', models.DecimalField(decimal_places=1, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('recommendation_confidence', models.DecimalField(decimal_places=2, help_text='Confidence score from collaborative filtering algorithm (0-100%)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('similarity_score', models.DecimalField(decimal_places=4, help_text='Cosine similarity from embedding vectors (0-1)', max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('paused', 'Paused'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('total_steps', models.PositiveIntegerField(default=0)),
                ('completed_steps', models.PositiveIntegerField(default=0)),
                ('completion_percentage', models.DecimalField(decimal_places=2, default=0, max_digits=5, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('personalization_factors', models.JSONField(default=dict, help_text='Factors used for personalization: learning_style, pace, interests, prior_knowledge')),
                ('similar_students', models.JSONField(default=list, help_text='Student IDs with similar learning patterns (collaborative filtering)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Learning Pathway',
                'verbose_name_plural': 'Learning Pathways',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student_id', '-created_at'], name='adaptive_pa_student_b7032e_idx'), models.Index(fields=['status', 'tenant'], name='adaptive_pa_status_11cad3_idx'), models.Index(fields=['difficulty_level'], name='adaptive_pa_difficu_078e40_idx')],
            },
        ),
        migrations.CreateModel(
            name='LearningStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True)),
                ('content_type', models.CharField(choices=[('video', 'Video Lesson'), ('reading', 'Reading Material'), ('quiz', 'Quiz/Assessment'), ('assignment', 'Assignment'), ('project', 'Project'), ('discussion', 'Discussion Forum'), ('interactive', 'Interactive Activity'), ('lab', 'Hands-on Lab')], max_length=20)),
                ('content_url', models.URLField(blank=True)),
                ('sequence_order', models.PositiveIntegerField()),
                ('is_prerequisite', models.BooleanField(default=False)),
                ('prerequisites', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Step numbers that must be completed first', size=None)),
                ('estimated_minutes', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('difficulty_rating', models.DecimalField(decimal_places=1, help_text='Difficulty rating 1-5', max_digits=3, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('learning_objectives', django.contrib.postgres.fields.ArrayField(base_field=models.TextField(), blank=True, default=list, size=None)),
                ('tags', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Content tags for similarity matching', size=None)),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('skipped', 'Skipped')], default='not_started', max_length=20)),
                ('completion_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='steps', to='adaptive_pathway.learningpathway')),
            ],
            options={
                'verbose_name': 'Learning Step',
                'verbose_name_plural': 'Learning Steps',
                'ordering': ['pathway', 'sequence_order'],
            },
        ),
        migrations.CreateModel(
            name='ContentEmbedding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('embedding_vector', django.contrib.postgres.fields.ArrayField(base_field=models.FloatField(), default=list, help_text='384-dimensional embedding vector from sentence-transformers', size=None)),
                ('embedding_dimension', models.PositiveIntegerField(default=384)),
                ('model_name', models.CharField(default='all-MiniLM-L6-v2', help_text='Name of the embedding model used', max_length=100)),
                ('text_content', models.TextField(help_text='Text used to generate embedding (title + description + objectives)')),
                ('similar_content', models.JSONField(default=list, help_text='Cached list of similar step_numbers with similarity scores')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('step', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='embedding', to='adaptive_pathway.learningstep')),
            ],
            options={
                'verbose_name': 'Content Embedding',
                'verbose_name_plural': 'Content Embeddings',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='PathwayRecommendation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recommendation_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('tenant', models.CharField(db_index=True, max_length=100)),
                ('student_id', models.CharField(db_index=True, max_length=100)),
                ('student_name', models.CharField(max_length=200)),
                ('algorithm_used', models.CharField(choices=[('collaborative_filtering', 'Collaborative Filtering'), ('content_based', 'Content-Based'), ('hybrid', 'Hybrid (CF + Embeddings)')], default='hybrid', max_length=30)),
                ('recommendation_score', models.DecimalField(decimal_places=4, help_text='Overall recommendation score (0-1)', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('collaborative_score', models.DecimalField(decimal_places=4, help_text='Score from collaborative filtering', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('embedding_similarity', models.DecimalField(decimal_places=4, help_text='Cosine similarity from content embeddings', max_digits=6, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('similar_students_count', models.PositiveIntegerField(default=0)),
                ('similar_students_list', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, default=list, help_text='Student IDs with similar learning patterns', size=None)),
                ('common_pathways', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Pathway numbers completed by similar students', size=None)),
                ('recommendation_reasons', models.JSONField(default=list, help_text='Human-readable reasons for recommendation')),
                ('is_accepted', models.BooleanField(blank=True, null=True)),
                ('feedback_score', models.IntegerField(blank=True, help_text='User rating of recommendation (1-5)', null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(help_text='Recommendation expiry date')),
                ('recommended_pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='adaptive_pathway.learningpathway')),
            ],
            options={
                'verbose_name': 'Pathway Recommendation',
                'verbose_name_plural': 'Pathway Recommendations',
                'ordering': ['-recommendation_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('progress_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('tenant', models.CharField(db_index=True, max_length=100)),
                ('student_id', models.CharField(db_index=True, max_length=100)),
                ('time_spent_minutes', models.PositiveIntegerField(default=0)),
                ('attempts', models.PositiveIntegerField(default=0)),
                ('completion_score', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('struggle_indicators', models.JSONField(default=dict, help_text='Indicators of difficulty: multiple_attempts, extended_time, help_requests')),
                ('engagement_level', models.CharField(choices=[('high', 'High Engagement'), ('medium', 'Medium Engagement'), ('low', 'Low Engagement')], default='medium', max_length=20)),
                ('recommended_next_steps', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=50), blank=True, default=list, help_text='Step numbers recommended based on performance', size=None)),
                ('difficulty_adjustment', models.CharField(choices=[('easier', 'Recommend Easier'), ('maintain', 'Maintain Level'), ('harder', 'Recommend Harder')], default='maintain', max_length=20)),
                ('is_completed', models.BooleanField(default=False)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('last_activity', models.DateTimeField(auto_now=True)),
                ('pathway', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='adaptive_pathway.learningpathway')),
                ('step', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progress_records', to='adaptive_pathway.learningstep')),
            ],
            options={
                'verbose_name': 'Student Progress',
                'verbose_name_plural': 'Student Progress Records',
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddIndex(
            model_name='learningstep',
            index=models.Index(fields=['pathway', 'sequence_order'], name='adaptive_pa_pathway_43bf9f_idx'),
        ),
        migrations.AddIndex(
            model_name='learningstep',
            index=models.Index(fields=['status'], name='adaptive_pa_status_f205eb_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='learningstep',
            unique_together={('pathway', 'sequence_order')},
        ),
        migrations.AddIndex(
            model_name='contentembedding',
            index=models.Index(fields=['step'], name='adaptive_pa_step_id_fe5e5f_idx'),
        ),
        migrations.AddIndex(
            model_name='pathwayrecommendation',
            index=models.Index(fields=['student_id', '-created_at'], name='adaptive_pa_student_a4b877_idx'),
        ),
        migrations.AddIndex(
            model_name='pathwayrecommendation',
            index=models.Index(fields=['is_accepted'], name='adaptive_pa_is_acce_fdd7a4_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprogress',
            index=models.Index(fields=['student_id', 'pathway'], name='adaptive_pa_student_f95a36_idx'),
        ),
        migrations.AddIndex(
            model_name='studentprogress',
            index=models.Index(fields=['step', 'is_completed'], name='adaptive_pa_step_id_64c15f_idx'),
        ),
    ]
