# Generated by Django 5.1.2 on 2025-10-27 09:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tenants", "0003_tenantapikey_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="MicroCredential",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=500)),
                (
                    "code",
                    models.CharField(help_text="Internal course code", max_length=100),
                ),
                ("description", models.TextField(blank=True)),
                (
                    "duration_hours",
                    models.PositiveIntegerField(help_text="Total duration in hours"),
                ),
                (
                    "delivery_mode",
                    models.CharField(
                        choices=[
                            ("online", "Online"),
                            ("face_to_face", "Face to Face"),
                            ("blended", "Blended"),
                            ("workplace", "Workplace"),
                        ],
                        default="blended",
                        max_length=50,
                    ),
                ),
                ("target_audience", models.TextField(blank=True)),
                (
                    "learning_outcomes",
                    models.JSONField(
                        default=list, help_text="List of learning outcomes"
                    ),
                ),
                (
                    "source_units",
                    models.JSONField(
                        default=list,
                        help_text="List of units used: [{code, title, nominal_hours, elements}]",
                    ),
                ),
                (
                    "compressed_content",
                    models.JSONField(
                        default=dict,
                        help_text="Compressed curriculum with key competencies and assessment tasks",
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list, help_text="Searchable tags for categorization"
                    ),
                ),
                (
                    "skills_covered",
                    models.JSONField(default=list, help_text="List of specific skills"),
                ),
                (
                    "industry_sectors",
                    models.JSONField(
                        default=list, help_text="Relevant industry sectors"
                    ),
                ),
                (
                    "aqf_level",
                    models.CharField(
                        blank=True, help_text="Equivalent AQF level", max_length=50
                    ),
                ),
                ("assessment_strategy", models.TextField(blank=True)),
                (
                    "assessment_tasks",
                    models.JSONField(
                        default=list,
                        help_text="List of assessment tasks with mapping to elements",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=10, null=True
                    ),
                ),
                (
                    "max_participants",
                    models.PositiveIntegerField(blank=True, null=True),
                ),
                ("prerequisites", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_review", "In Review"),
                            ("approved", "Approved"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=50,
                    ),
                ),
                ("gpt_generated", models.BooleanField(default=False)),
                ("gpt_model_used", models.CharField(blank=True, max_length=100)),
                ("generation_time_seconds", models.FloatField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_micro_credentials",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="micro_credentials",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("tenant", "code")},
            },
        ),
        migrations.CreateModel(
            name="MicroCredentialEnrollment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("student_name", models.CharField(max_length=200)),
                ("student_email", models.EmailField(max_length=254)),
                ("student_id", models.CharField(blank=True, max_length=100)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("enrolled", "Enrolled"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("withdrawn", "Withdrawn"),
                        ],
                        default="enrolled",
                        max_length=50,
                    ),
                ),
                ("enrolled_at", models.DateTimeField(auto_now_add=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("withdrawn_at", models.DateTimeField(blank=True, null=True)),
                (
                    "progress_data",
                    models.JSONField(
                        default=dict,
                        help_text="Track completion of learning outcomes and assessments",
                    ),
                ),
                (
                    "micro_credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="enrollments",
                        to="micro_credential.microcredential",
                    ),
                ),
            ],
            options={
                "ordering": ["-enrolled_at"],
                "unique_together": {("micro_credential", "student_email")},
            },
        ),
        migrations.CreateModel(
            name="MicroCredentialVersion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("change_summary", models.TextField()),
                (
                    "content_snapshot",
                    models.JSONField(
                        help_text="Full snapshot of the micro-credential at this version"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "micro_credential",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="versions",
                        to="micro_credential.microcredential",
                    ),
                ),
            ],
            options={
                "ordering": ["-version_number"],
                "unique_together": {("micro_credential", "version_number")},
            },
        ),
    ]
