# Generated by Django 5.1.2 on 2025-10-24 02:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EvidenceMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mapping_number', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('assessment_type', models.CharField(choices=[('written', 'Written Assignment'), ('practical', 'Practical Demonstration'), ('portfolio', 'Portfolio'), ('project', 'Project Work'), ('presentation', 'Presentation')], default='written', max_length=50)),
                ('assessment_title', models.CharField(max_length=200)),
                ('unit_code', models.CharField(blank=True, max_length=50)),
                ('total_criteria', models.IntegerField(default=0)),
                ('total_submissions', models.IntegerField(default=0)),
                ('auto_extract_text', models.BooleanField(default=True, help_text='Automatically extract text from submissions')),
                ('generate_embeddings', models.BooleanField(default=True, help_text='Generate embeddings for semantic search')),
                ('require_evidence_per_criterion', models.BooleanField(default=True)),
                ('min_evidence_length', models.IntegerField(default=50, help_text='Minimum characters for valid evidence')),
                ('total_evidence_tagged', models.IntegerField(default=0)),
                ('total_text_extracted', models.IntegerField(default=0)),
                ('embeddings_generated', models.IntegerField(default=0)),
                ('coverage_percentage', models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', 'created_at'], name='evidence_ma_status_33eb5b_idx'), models.Index(fields=['assessment_type'], name='evidence_ma_assessm_982127_idx'), models.Index(fields=['unit_code'], name='evidence_ma_unit_co_cee860_idx')],
            },
        ),
        migrations.CreateModel(
            name='SubmissionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evidence_number', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('student_id', models.CharField(max_length=100)),
                ('student_name', models.CharField(max_length=200)),
                ('submission_id', models.CharField(max_length=100)),
                ('submission_title', models.CharField(blank=True, max_length=200)),
                ('submission_type', models.CharField(blank=True, help_text='e.g., PDF, DOCX, Video', max_length=50)),
                ('file_path', models.CharField(blank=True, max_length=500)),
                ('file_size_bytes', models.BigIntegerField(blank=True, null=True)),
                ('extracted_text', models.TextField(blank=True, help_text='Full text extracted from submission')),
                ('text_length', models.IntegerField(default=0)),
                ('extraction_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('extraction_method', models.CharField(blank=True, help_text='e.g., OCR, PDF parser, Speech-to-text', max_length=100)),
                ('text_embedding', models.JSONField(default=list, help_text='Vector embedding for semantic search')),
                ('embedding_model', models.CharField(blank=True, help_text='e.g., sentence-transformers', max_length=100)),
                ('embedding_dimension', models.IntegerField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict, help_text='Additional submission metadata (language, readability, keywords, etc.)')),
                ('total_tags', models.IntegerField(default=0)),
                ('criteria_covered', models.JSONField(default=list, help_text='List of criterion IDs with evidence')),
                ('submitted_at', models.DateTimeField()),
                ('extracted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='evidence_mapper.evidencemapping')),
            ],
            options={
                'ordering': ['-submitted_at'],
            },
        ),
        migrations.CreateModel(
            name='CriteriaTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_number', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('criterion_id', models.CharField(help_text='Reference to assessment criterion', max_length=100)),
                ('criterion_name', models.CharField(max_length=200)),
                ('criterion_description', models.TextField(blank=True)),
                ('tagged_text', models.TextField(help_text='Excerpt from submission linked to criterion')),
                ('text_start_position', models.IntegerField(help_text='Character position in original text')),
                ('text_end_position', models.IntegerField()),
                ('context_before', models.TextField(blank=True, help_text='Text before tagged excerpt')),
                ('context_after', models.TextField(blank=True, help_text='Text after tagged excerpt')),
                ('tag_type', models.CharField(choices=[('direct', 'Direct Evidence'), ('indirect', 'Indirect Evidence'), ('supporting', 'Supporting Material'), ('reference', 'Reference/Citation')], default='direct', max_length=20)),
                ('confidence_level', models.CharField(choices=[('high', 'High Confidence'), ('medium', 'Medium Confidence'), ('low', 'Low Confidence'), ('manual', 'Manually Tagged')], default='manual', max_length=20)),
                ('confidence_score', models.FloatField(default=1.0, help_text='Automated confidence score (0-1)', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('notes', models.TextField(blank=True, help_text='Assessor notes about this evidence')),
                ('keywords', models.JSONField(default=list, help_text='Extracted keywords from tagged text')),
                ('is_validated', models.BooleanField(default=False)),
                ('validated_by', models.CharField(blank=True, max_length=100)),
                ('validated_at', models.DateTimeField(blank=True, null=True)),
                ('tagged_by', models.CharField(max_length=100)),
                ('tagged_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='evidence_mapper.submissionevidence')),
            ],
            options={
                'ordering': ['-tagged_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('mapping_created', 'Mapping Created'), ('submission_added', 'Submission Added'), ('text_extracted', 'Text Extracted'), ('embedding_generated', 'Embedding Generated'), ('evidence_tagged', 'Evidence Tagged'), ('tag_validated', 'Tag Validated'), ('tag_removed', 'Tag Removed'), ('search_performed', 'Search Performed'), ('export_generated', 'Export Generated')], max_length=50)),
                ('description', models.TextField()),
                ('submission_id', models.CharField(blank=True, max_length=100)),
                ('criterion_id', models.CharField(blank=True, max_length=100)),
                ('tag_id', models.IntegerField(blank=True, null=True)),
                ('action_data', models.JSONField(default=dict, help_text='Detailed data about the action performed')),
                ('changes_made', models.JSONField(default=dict, help_text='Before/after values for modifications')),
                ('processing_time_ms', models.IntegerField(blank=True, null=True)),
                ('performed_by', models.CharField(max_length=100)),
                ('user_role', models.CharField(blank=True, max_length=50)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=500)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='evidence_mapper.evidencemapping')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['mapping', 'action'], name='evidence_ma_mapping_ff8d15_idx'), models.Index(fields=['timestamp'], name='evidence_ma_timesta_b631cc_idx'), models.Index(fields=['performed_by'], name='evidence_ma_perform_e7efb5_idx')],
            },
        ),
        migrations.CreateModel(
            name='EmbeddingSearch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('search_number', models.CharField(blank=True, editable=False, max_length=50, unique=True)),
                ('search_type', models.CharField(choices=[('similarity', 'Similarity Search'), ('criteria_match', 'Criteria Matching'), ('keyword', 'Keyword Search'), ('hybrid', 'Hybrid Search')], max_length=20)),
                ('query_text', models.TextField()),
                ('query_embedding', models.JSONField(default=list, help_text='Vector embedding of query')),
                ('filter_criteria', models.JSONField(default=dict, help_text='Additional filters (student, date range, etc.)')),
                ('results_count', models.IntegerField(default=0)),
                ('top_results', models.JSONField(default=list, help_text='Top matching results with scores')),
                ('search_time_ms', models.IntegerField(help_text='Search execution time')),
                ('performed_by', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='searches', to='evidence_mapper.evidencemapping')),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['mapping', 'search_type'], name='evidence_ma_mapping_7bc7d2_idx'), models.Index(fields=['timestamp'], name='evidence_ma_timesta_663650_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='submissionevidence',
            index=models.Index(fields=['mapping', 'student_id'], name='evidence_ma_mapping_7af8ee_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionevidence',
            index=models.Index(fields=['extraction_status'], name='evidence_ma_extract_ed9e52_idx'),
        ),
        migrations.AddIndex(
            model_name='submissionevidence',
            index=models.Index(fields=['submitted_at'], name='evidence_ma_submitt_1780bb_idx'),
        ),
        migrations.AddIndex(
            model_name='criteriatag',
            index=models.Index(fields=['evidence', 'criterion_id'], name='evidence_ma_evidenc_bb9383_idx'),
        ),
        migrations.AddIndex(
            model_name='criteriatag',
            index=models.Index(fields=['tag_type'], name='evidence_ma_tag_typ_ce1b39_idx'),
        ),
        migrations.AddIndex(
            model_name='criteriatag',
            index=models.Index(fields=['confidence_level'], name='evidence_ma_confide_61b5af_idx'),
        ),
        migrations.AddIndex(
            model_name='criteriatag',
            index=models.Index(fields=['is_validated'], name='evidence_ma_is_vali_1af91a_idx'),
        ),
    ]
