# Generated by Django 5.1.2 on 2025-10-24 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('evidence_mapper', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='embeddingsearch',
            name='search_time_ms',
            field=models.IntegerField(blank=True, help_text='Search execution time', null=True),
        ),
        migrations.AlterField(
            model_name='evidencemapping',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='submissionevidence',
            name='submitted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
