# Generated by Django 5.1.2 on 2025-10-24 03:23

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("assessment_builder", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuthenticityCheck",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "check_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("name", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "plagiarism_threshold",
                    models.FloatField(
                        default=0.7,
                        help_text="Similarity threshold for plagiarism detection (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                ("metadata_verification_enabled", models.BooleanField(default=True)),
                ("anomaly_detection_enabled", models.BooleanField(default=True)),
                (
                    "academic_integrity_mode",
                    models.BooleanField(
                        default=True,
                        help_text="Enable strict academic integrity compliance",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("flagged", "Flagged"),
                            ("reviewed", "Reviewed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_submissions_checked", models.IntegerField(default=0)),
                ("plagiarism_cases_detected", models.IntegerField(default=0)),
                ("metadata_issues_found", models.IntegerField(default=0)),
                ("anomalies_detected", models.IntegerField(default=0)),
                (
                    "overall_integrity_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Overall integrity score (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="authenticity_checks",
                        to="assessment_builder.assessment",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="authenticity_checks_created",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Authenticity Check",
                "verbose_name_plural": "Authenticity Checks",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="SubmissionAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("submission_id", models.CharField(max_length=100)),
                ("student_id", models.CharField(blank=True, max_length=100)),
                ("student_name", models.CharField(blank=True, max_length=255)),
                ("submission_content", models.TextField()),
                ("content_hash", models.CharField(editable=False, max_length=64)),
                ("word_count", models.IntegerField(default=0)),
                ("character_count", models.IntegerField(default=0)),
                (
                    "content_embedding",
                    models.JSONField(
                        default=list,
                        help_text="384-dimensional embedding vector for similarity comparison",
                    ),
                ),
                (
                    "plagiarism_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Plagiarism similarity score (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "metadata_verification_score",
                    models.FloatField(
                        default=100.0,
                        help_text="Metadata verification score (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "anomaly_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Anomaly detection score (0-100, higher is more suspicious)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "combined_integrity_score",
                    models.FloatField(
                        default=100.0,
                        help_text="Combined integrity score (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "integrity_status",
                    models.CharField(
                        choices=[
                            ("pass", "Pass"),
                            ("warning", "Warning"),
                            ("fail", "Fail"),
                            ("under_review", "Under Review"),
                        ],
                        default="pass",
                        max_length=20,
                    ),
                ),
                ("plagiarism_detected", models.BooleanField(default=False)),
                ("metadata_issues", models.BooleanField(default=False)),
                ("anomalies_found", models.BooleanField(default=False)),
                (
                    "analysis_metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Additional analysis metadata (language, typing patterns, etc.)",
                    ),
                ),
                ("analyzed_at", models.DateTimeField(auto_now_add=True)),
                (
                    "authenticity_check",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="submission_analyses",
                        to="authenticity_check.authenticitycheck",
                    ),
                ),
            ],
            options={
                "verbose_name": "Submission Analysis",
                "verbose_name_plural": "Submission Analyses",
                "ordering": ["-analyzed_at"],
            },
        ),
        migrations.CreateModel(
            name="PlagiarismMatch",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "match_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "similarity_score",
                    models.FloatField(
                        help_text="Similarity score between submissions (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "match_type",
                    models.CharField(
                        choices=[
                            ("exact", "Exact Match"),
                            ("paraphrased", "Paraphrased"),
                            ("structural", "Structural Similarity"),
                            ("embedding", "Embedding Similarity"),
                        ],
                        default="embedding",
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "matched_text_segments",
                    models.JSONField(
                        default=list,
                        help_text="List of matched text segments with positions",
                    ),
                ),
                ("matched_words_count", models.IntegerField(default=0)),
                (
                    "matched_percentage",
                    models.FloatField(
                        default=0.0,
                        help_text="Percentage of text that matches",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("reviewed", models.BooleanField(default=False)),
                ("false_positive", models.BooleanField(default=False)),
                ("review_notes", models.TextField(blank=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "matched_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plagiarism_matches_as_match",
                        to="authenticity_check.submissionanalysis",
                    ),
                ),
                (
                    "source_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="plagiarism_matches_as_source",
                        to="authenticity_check.submissionanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Plagiarism Match",
                "verbose_name_plural": "Plagiarism Matches",
                "ordering": ["-similarity_score", "-detected_at"],
            },
        ),
        migrations.CreateModel(
            name="MetadataVerification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "verification_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "file_metadata",
                    models.JSONField(
                        default=dict,
                        help_text="Complete file metadata (EXIF, document properties, etc.)",
                    ),
                ),
                ("creation_timestamp", models.DateTimeField(blank=True, null=True)),
                ("modification_timestamp", models.DateTimeField(blank=True, null=True)),
                (
                    "modification_history",
                    models.JSONField(
                        default=list, help_text="History of file modifications"
                    ),
                ),
                (
                    "author_info",
                    models.JSONField(
                        default=dict,
                        help_text="Author metadata from file (if available)",
                    ),
                ),
                ("author_matches_student", models.BooleanField(blank=True, null=True)),
                (
                    "verification_status",
                    models.CharField(
                        choices=[
                            ("verified", "Verified"),
                            ("suspicious", "Suspicious"),
                            ("anomalous", "Anomalous"),
                            ("failed", "Failed"),
                        ],
                        default="verified",
                        max_length=20,
                    ),
                ),
                (
                    "anomalies_detected",
                    models.JSONField(
                        default=list, help_text="List of detected metadata anomalies"
                    ),
                ),
                (
                    "verification_score",
                    models.FloatField(
                        default=100.0,
                        help_text="Verification score (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("verified_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata_verifications",
                        to="authenticity_check.submissionanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Metadata Verification",
                "verbose_name_plural": "Metadata Verifications",
                "ordering": ["-verified_at"],
            },
        ),
        migrations.CreateModel(
            name="AnomalyDetection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "anomaly_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "anomaly_type",
                    models.CharField(
                        choices=[
                            ("typing_speed", "Unusual Typing Speed"),
                            ("paste_events", "Excessive Paste Events"),
                            ("time_gaps", "Suspicious Time Gaps"),
                            ("behavioral", "Behavioral Anomaly"),
                            ("pattern", "Pattern Anomaly"),
                            ("statistical", "Statistical Anomaly"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "anomaly_data",
                    models.JSONField(
                        default=dict, help_text="Detailed anomaly data and evidence"
                    ),
                ),
                ("description", models.TextField()),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.5,
                        help_text="Confidence in anomaly detection (0.0-1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "impact_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Impact on integrity score (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("acknowledged", models.BooleanField(default=False)),
                ("false_positive", models.BooleanField(default=False)),
                ("resolution_notes", models.TextField(blank=True)),
                ("detected_at", models.DateTimeField(auto_now_add=True)),
                (
                    "submission_analysis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="anomaly_detections",
                        to="authenticity_check.submissionanalysis",
                    ),
                ),
            ],
            options={
                "verbose_name": "Anomaly Detection",
                "verbose_name_plural": "Anomaly Detections",
                "ordering": ["-severity", "-detected_at"],
            },
        ),
    ]
