# Generated by Django 5.1.2 on 2025-10-24 11:11

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('tenant', models.CharField(db_index=True, max_length=100)),
                ('trainer_id', models.CharField(db_index=True, max_length=100)),
                ('trainer_name', models.CharField(max_length=200)),
                ('summary_date', models.DateField(db_index=True)),
                ('total_sessions', models.IntegerField(default=0)),
                ('total_teaching_hours', models.FloatField(default=0.0)),
                ('total_students', models.IntegerField(default=0)),
                ('courses_taught', models.JSONField(default=list)),
                ('daily_highlights', models.TextField(blank=True)),
                ('overall_student_engagement', models.TextField(blank=True)),
                ('key_achievements', models.JSONField(default=list)),
                ('challenges_summary', models.TextField(blank=True)),
                ('action_items_pending', models.JSONField(default=list)),
                ('diary_entries_included', models.JSONField(default=list)),
                ('evidence_documents_created', models.IntegerField(default=0)),
                ('generated_by_model', models.CharField(blank=True, max_length=100)),
                ('generation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-summary_date'],
                'unique_together': {('tenant', 'trainer_id', 'summary_date')},
            },
        ),
        migrations.CreateModel(
            name='DiaryEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entry_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('tenant', models.CharField(db_index=True, max_length=100)),
                ('trainer_id', models.CharField(db_index=True, max_length=100)),
                ('trainer_name', models.CharField(max_length=200)),
                ('session_date', models.DateField(default=django.utils.timezone.now)),
                ('session_time_start', models.TimeField(blank=True, null=True)),
                ('session_time_end', models.TimeField(blank=True, null=True)),
                ('session_duration_minutes', models.IntegerField(default=0)),
                ('course_name', models.CharField(max_length=300)),
                ('course_code', models.CharField(blank=True, max_length=100)),
                ('unit_of_competency', models.CharField(blank=True, max_length=200)),
                ('student_count', models.IntegerField(default=0)),
                ('delivery_mode', models.CharField(choices=[('face_to_face', 'Face to Face'), ('online_live', 'Online Live'), ('online_self_paced', 'Online Self-Paced'), ('blended', 'Blended'), ('workplace', 'Workplace')], default='face_to_face', max_length=50)),
                ('raw_transcript', models.TextField(blank=True)),
                ('manual_notes', models.TextField(blank=True)),
                ('session_summary', models.TextField(blank=True)),
                ('key_topics_covered', models.JSONField(default=list)),
                ('student_engagement_notes', models.TextField(blank=True)),
                ('challenges_encountered', models.TextField(blank=True)),
                ('follow_up_actions', models.JSONField(default=list)),
                ('learning_outcomes_addressed', models.JSONField(default=list)),
                ('assessment_activities', models.TextField(blank=True)),
                ('resources_used', models.JSONField(default=list)),
                ('evidence_attachments', models.JSONField(default=list)),
                ('transcription_model', models.CharField(blank=True, max_length=100)),
                ('summarization_model', models.CharField(blank=True, max_length=100)),
                ('transcription_duration_seconds', models.FloatField(blank=True, null=True)),
                ('summarization_tokens', models.IntegerField(blank=True, null=True)),
                ('entry_status', models.CharField(choices=[('draft', 'Draft'), ('transcribing', 'Transcribing'), ('summarizing', 'Summarizing'), ('complete', 'Complete'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('is_pinned', models.BooleanField(default=False)),
                ('is_shared', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-session_date', '-created_at'],
                'indexes': [models.Index(fields=['tenant', 'trainer_id', '-session_date'], name='trainer_dia_tenant_58863e_idx'), models.Index(fields=['session_date', 'entry_status'], name='trainer_dia_session_4e3472_idx'), models.Index(fields=['course_code', '-session_date'], name='trainer_dia_course__8bfe60_idx')],
            },
        ),
        migrations.CreateModel(
            name='AudioRecording',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recording_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('recording_filename', models.CharField(max_length=500)),
                ('recording_file_path', models.CharField(max_length=1000)),
                ('recording_file_size_mb', models.FloatField(default=0.0)),
                ('recording_duration_seconds', models.FloatField(default=0.0)),
                ('recording_format', models.CharField(default='mp3', max_length=20)),
                ('transcript_text', models.TextField(blank=True)),
                ('transcript_confidence', models.FloatField(blank=True, null=True)),
                ('transcript_language', models.CharField(default='en', max_length=10)),
                ('processing_status', models.CharField(choices=[('uploaded', 'Uploaded'), ('queued', 'Queued for Processing'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='uploaded', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('diary_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recordings', to='trainer_diary.diaryentry')),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
        migrations.CreateModel(
            name='EvidenceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('document_type', models.CharField(choices=[('session_plan', 'Session Plan'), ('attendance_record', 'Attendance Record'), ('teaching_evidence', 'Teaching Evidence'), ('assessment_record', 'Assessment Record'), ('student_feedback', 'Student Feedback Summary'), ('compliance_report', 'Compliance Report'), ('professional_reflection', 'Professional Reflection')], max_length=50)),
                ('document_title', models.CharField(max_length=300)),
                ('document_content', models.TextField()),
                ('document_format', models.CharField(choices=[('markdown', 'Markdown'), ('html', 'HTML'), ('pdf', 'PDF'), ('docx', 'Word Document')], default='markdown', max_length=20)),
                ('file_path', models.CharField(blank=True, max_length=1000)),
                ('file_size_kb', models.FloatField(blank=True, null=True)),
                ('generated_by', models.CharField(max_length=200)),
                ('generation_method', models.CharField(choices=[('auto_ai', 'Auto-generated by AI'), ('template', 'Generated from Template'), ('manual', 'Manually Created')], default='auto_ai', max_length=50)),
                ('meets_compliance_standards', models.BooleanField(default=True)),
                ('compliance_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('diary_entry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence_docs', to='trainer_diary.diaryentry')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='TranscriptionJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_number', models.CharField(db_index=True, max_length=50, unique=True)),
                ('job_status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('transcription_engine', models.CharField(choices=[('whisper', 'OpenAI Whisper'), ('google_stt', 'Google Speech-to-Text'), ('azure_stt', 'Azure Speech Service'), ('aws_transcribe', 'AWS Transcribe')], default='whisper', max_length=50)),
                ('language', models.CharField(default='en', max_length=10)),
                ('enable_speaker_diarization', models.BooleanField(default=False)),
                ('enable_punctuation', models.BooleanField(default=True)),
                ('transcript_result', models.TextField(blank=True)),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('processing_time_seconds', models.FloatField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True)),
                ('retry_count', models.IntegerField(default=0)),
                ('max_retries', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('audio_recording', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transcription_jobs', to='trainer_diary.audiorecording')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
