# Generated by Django 5.1.2 on 2025-10-24 13:22

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConversationThread",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "thread_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("tenant", models.CharField(db_index=True, max_length=100)),
                ("student_email", models.EmailField(max_length=254)),
                ("student_name", models.CharField(max_length=200)),
                ("subject", models.CharField(max_length=500)),
                ("message_count", models.IntegerField(default=0)),
                (
                    "first_message_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "last_message_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("is_resolved", models.BooleanField(default=False)),
                ("resolved_at", models.DateTimeField(blank=True, null=True)),
                ("primary_category", models.CharField(blank=True, max_length=100)),
                ("tags", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-last_message_date"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "is_active"],
                        name="email_assis_tenant_ff757b_idx",
                    ),
                    models.Index(
                        fields=["student_email", "-last_message_date"],
                        name="email_assis_student_bf1911_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="MessageTemplate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "template_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("tenant", models.CharField(db_index=True, max_length=100)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "template_type",
                    models.CharField(
                        choices=[
                            ("assessment", "Assessment Query"),
                            ("enrollment", "Enrollment"),
                            ("technical", "Technical Support"),
                            ("extension", "Extension Request"),
                            ("general", "General Query"),
                            ("complaint", "Complaint"),
                            ("feedback", "Feedback"),
                        ],
                        max_length=50,
                    ),
                ),
                ("template_body", models.TextField()),
                ("placeholders", models.JSONField(blank=True, default=list)),
                (
                    "default_tone",
                    models.CharField(default="professional", max_length=50),
                ),
                ("formality_level", models.IntegerField(default=3)),
                ("usage_count", models.IntegerField(default=0)),
                ("success_rate", models.FloatField(default=0.0)),
                ("last_used_at", models.DateTimeField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("is_system_template", models.BooleanField(default=False)),
                ("created_by", models.CharField(blank=True, max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-usage_count", "name"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "template_type"],
                        name="email_assis_tenant_974d89_idx",
                    ),
                    models.Index(
                        fields=["is_active", "-usage_count"],
                        name="email_assis_is_acti_b5c3de_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="DraftReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "draft_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("reply_body", models.TextField()),
                ("reply_subject", models.CharField(blank=True, max_length=500)),
                ("tone_used", models.CharField(max_length=50)),
                ("formality_level", models.IntegerField(default=3)),
                ("include_greeting", models.BooleanField(default=True)),
                ("include_signature", models.BooleanField(default=True)),
                ("confidence_score", models.FloatField(default=0.0)),
                ("readability_score", models.FloatField(default=0.0)),
                ("word_count", models.IntegerField(default=0)),
                ("estimated_reading_time_seconds", models.IntegerField(default=0)),
                ("was_edited", models.BooleanField(default=False)),
                ("was_sent", models.BooleanField(default=False)),
                ("was_rejected", models.BooleanField(default=False)),
                ("rejection_reason", models.TextField(blank=True)),
                (
                    "generation_status",
                    models.CharField(
                        choices=[
                            ("generating", "Generating"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="completed",
                        max_length=20,
                    ),
                ),
                ("generation_time_ms", models.IntegerField(default=0)),
                ("llm_model_used", models.CharField(default="gpt-4", max_length=100)),
                ("generation_prompt", models.TextField(blank=True)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
                ("sent_at", models.DateTimeField(blank=True, null=True)),
                (
                    "template_used",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="email_assistant.messagetemplate",
                    ),
                ),
            ],
            options={
                "ordering": ["-generated_at"],
            },
        ),
        migrations.CreateModel(
            name="StudentMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "message_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("tenant", models.CharField(db_index=True, max_length=100)),
                ("student_name", models.CharField(max_length=200)),
                ("student_email", models.EmailField(max_length=254)),
                ("student_id", models.CharField(blank=True, max_length=50)),
                (
                    "message_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("lms", "LMS Message"),
                            ("sms", "SMS"),
                            ("chat", "Live Chat"),
                            ("form", "Contact Form"),
                        ],
                        default="email",
                        max_length=20,
                    ),
                ),
                ("subject", models.CharField(max_length=500)),
                ("message_body", models.TextField()),
                (
                    "received_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("category", models.CharField(blank=True, max_length=100)),
                ("detected_sentiment", models.CharField(blank=True, max_length=50)),
                ("detected_topics", models.JSONField(blank=True, default=list)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("new", "New"),
                            ("draft_generated", "Draft Generated"),
                            ("replied", "Replied"),
                            ("archived", "Archived"),
                        ],
                        default="new",
                        max_length=30,
                    ),
                ),
                ("requires_human_review", models.BooleanField(default=False)),
                ("previous_message_count", models.IntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "conversation_thread",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="messages",
                        to="email_assistant.conversationthread",
                    ),
                ),
            ],
            options={
                "ordering": ["-received_date"],
            },
        ),
        migrations.CreateModel(
            name="ReplyHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "history_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("final_reply_body", models.TextField()),
                ("final_subject", models.CharField(max_length=500)),
                ("time_to_first_draft_seconds", models.IntegerField(default=0)),
                ("time_to_send_seconds", models.IntegerField(default=0)),
                ("edit_count", models.IntegerField(default=0)),
                ("estimated_manual_time_seconds", models.IntegerField(default=300)),
                ("time_saved_seconds", models.IntegerField(default=0)),
                ("time_saved_percentage", models.FloatField(default=0.0)),
                ("sent_by", models.CharField(max_length=200)),
                ("sent_at", models.DateTimeField(default=django.utils.timezone.now)),
                ("student_responded", models.BooleanField(default=False)),
                ("student_satisfied", models.BooleanField(blank=True, null=True)),
                ("follow_up_required", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "draft_reply",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="email_assistant.draftreply",
                    ),
                ),
                (
                    "student_message",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reply_history",
                        to="email_assistant.studentmessage",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Reply histories",
                "ordering": ["-sent_at"],
            },
        ),
        migrations.AddField(
            model_name="draftreply",
            name="student_message",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="drafts",
                to="email_assistant.studentmessage",
            ),
        ),
        migrations.CreateModel(
            name="ToneProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("tenant", models.CharField(db_index=True, max_length=100)),
                ("name", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                ("tone_descriptor", models.CharField(max_length=50)),
                ("formality_level", models.IntegerField(default=3)),
                ("empathy_level", models.IntegerField(default=3)),
                ("brevity_level", models.IntegerField(default=3)),
                ("use_contractions", models.BooleanField(default=True)),
                ("use_emojis", models.BooleanField(default=False)),
                (
                    "greeting_style",
                    models.CharField(default="Hi {name},", max_length=100),
                ),
                (
                    "closing_style",
                    models.CharField(default="Best regards,", max_length=100),
                ),
                ("recommended_for", models.JSONField(blank=True, default=list)),
                ("usage_count", models.IntegerField(default=0)),
                ("is_default", models.BooleanField(default=False)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-is_default", "-usage_count", "name"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "is_active"],
                        name="email_assis_tenant_20722e_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="studentmessage",
            index=models.Index(
                fields=["tenant", "status"], name="email_assis_tenant_5f8974_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="studentmessage",
            index=models.Index(
                fields=["priority", "-received_date"],
                name="email_assis_priorit_19e18d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="studentmessage",
            index=models.Index(
                fields=["student_email", "-received_date"],
                name="email_assis_student_e863b0_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="replyhistory",
            index=models.Index(
                fields=["-sent_at"], name="email_assis_sent_at_8342dd_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="replyhistory",
            index=models.Index(
                fields=["sent_by", "-sent_at"], name="email_assis_sent_by_e5bcd0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="draftreply",
            index=models.Index(
                fields=["student_message", "-generated_at"],
                name="email_assis_student_5fdd1d_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="draftreply",
            index=models.Index(
                fields=["was_sent", "-generated_at"],
                name="email_assis_was_sen_e66d68_idx",
            ),
        ),
    ]
