# Generated by Django 5.1.13 on 2025-11-15 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenantapikey_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='abn',
            field=models.CharField(blank=True, help_text='Australian Business Number (11 digits)', max_length=11),
        ),
        migrations.AddField(
            model_name='tenant',
            name='acn',
            field=models.CharField(blank=True, help_text='Australian Company Number (9 digits, required for companies)', max_length=9),
        ),
        migrations.AddField(
            model_name='tenant',
            name='business_structure',
            field=models.CharField(blank=True, choices=[('sole_trader', 'Sole Trader'), ('partnership', 'Partnership'), ('company', 'Company (Pty Ltd)'), ('trust', 'Trust'), ('incorporated_association', 'Incorporated Association')], help_text='Legal structure of the business', max_length=30),
        ),
        migrations.AddField(
            model_name='tenant',
            name='postal_address',
            field=models.TextField(blank=True, help_text='Postal address (if different from registered address)'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='registered_address',
            field=models.TextField(blank=True, help_text='Registered business address'),
        ),
        migrations.AddField(
            model_name='tenant',
            name='registered_business_name',
            field=models.CharField(blank=True, help_text='ASIC-registered business name', max_length=255),
        ),
        migrations.AddField(
            model_name='tenant',
            name='trading_name',
            field=models.CharField(blank=True, help_text='Trading name (if different from registered name)', max_length=255),
        ),
    ]
