# Generated by Django 5.1.13 on 2025-11-16 03:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0004_tenant_abn_tenant_acn_tenant_business_structure_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='gst_registered',
            field=models.BooleanField(default=False, help_text='Is the business registered for GST?'),
        ),
    ]
