# Generated by Django 5.1.2 on 2025-11-02 00:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tas", "0003_compliancerule_facility_coursetas_immutablesnapshot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="TASTemplateSection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_name",
                    models.CharField(
                        help_text="Display name for the section (e.g., 'Cohort Profile')",
                        max_length=200,
                    ),
                ),
                (
                    "section_code",
                    models.CharField(
                        help_text="Unique code for the section (e.g., 'cohort_profile')",
                        max_length=50,
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="Help text/context for content creators"
                    ),
                ),
                (
                    "content_type",
                    models.CharField(
                        choices=[
                            ("text", "Plain Text"),
                            ("rich_text", "Rich Text / HTML"),
                            ("table", "Table"),
                            ("list", "Bulleted/Numbered List"),
                            ("json", "JSON Data"),
                        ],
                        default="rich_text",
                        max_length=20,
                    ),
                ),
                (
                    "default_content",
                    models.TextField(
                        blank=True,
                        help_text="Default/placeholder content for this section",
                    ),
                ),
                (
                    "is_editable",
                    models.BooleanField(
                        default=True, help_text="Whether users can edit this section"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this section is required in the TAS document",
                    ),
                ),
                (
                    "section_order",
                    models.IntegerField(
                        default=0, help_text="Display order within the template"
                    ),
                ),
                (
                    "gpt_prompt",
                    models.TextField(
                        blank=True,
                        help_text="GPT-4 prompt for auto-generating this section",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "parent_section",
                    models.ForeignKey(
                        blank=True,
                        help_text="Parent section for nested structure",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="subsections",
                        to="tas.tastemplatesection",
                    ),
                ),
                (
                    "template",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sections",
                        to="tas.tastemplate",
                    ),
                ),
            ],
            options={
                "verbose_name": "TAS Template Section",
                "verbose_name_plural": "TAS Template Sections",
                "db_table": "tas_template_sections",
                "ordering": ["template", "section_order", "section_name"],
                "indexes": [
                    models.Index(
                        fields=["template", "section_order"],
                        name="tas_templat_templat_b659fd_idx",
                    ),
                    models.Index(
                        fields=["section_code"], name="tas_templat_section_1be16a_idx"
                    ),
                ],
                "unique_together": {("template", "section_code")},
            },
        ),
    ]
