# Generated by Django 5.1.2 on 2025-11-02 00:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("tas", "0004_tastemplatesection"),
    ]

    operations = [
        migrations.CreateModel(
            name="TASTemplateSectionAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "section_order",
                    models.IntegerField(
                        default=0, help_text="Display order within this template"
                    ),
                ),
                (
                    "is_required",
                    models.BooleanField(
                        default=True,
                        help_text="Whether this section is required in this template",
                    ),
                ),
                (
                    "custom_label",
                    models.CharField(
                        blank=True,
                        help_text="Override section name for this template (optional)",
                        max_length=200,
                    ),
                ),
                (
                    "custom_description",
                    models.TextField(
                        blank=True,
                        help_text="Override description for this template (optional)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Template Section Assignment",
                "verbose_name_plural": "Template Section Assignments",
                "db_table": "tas_template_section_assignments",
                "ordering": ["template", "section_order"],
            },
        ),
        migrations.AlterModelOptions(
            name="tastemplatesection",
            options={
                "ordering": ["section_name"],
                "verbose_name": "TAS Template Section",
                "verbose_name_plural": "TAS Template Sections",
            },
        ),
        migrations.RemoveIndex(
            model_name="tastemplatesection",
            name="tas_templat_templat_b659fd_idx",
        ),
        migrations.AlterUniqueTogether(
            name="tastemplatesection",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="tastemplatesection",
            name="is_active",
            field=models.BooleanField(
                default=True, help_text="Whether this section is available for use"
            ),
        ),
        migrations.AlterField(
            model_name="tastemplatesection",
            name="parent_section",
            field=models.ForeignKey(
                blank=True,
                help_text="Parent section for nested structure",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="subsections",
                to="tas.tastemplatesection",
            ),
        ),
        migrations.AlterField(
            model_name="tastemplatesection",
            name="section_code",
            field=models.CharField(
                help_text="Unique code for the section (e.g., 'cohort_profile')",
                max_length=50,
                unique=True,
            ),
        ),
        migrations.AddIndex(
            model_name="tastemplatesection",
            index=models.Index(
                fields=["is_active"], name="tas_templat_is_acti_31d28e_idx"
            ),
        ),
        migrations.AddField(
            model_name="tastemplatesectionassignment",
            name="section",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="template_assignments",
                to="tas.tastemplatesection",
            ),
        ),
        migrations.AddField(
            model_name="tastemplatesectionassignment",
            name="template",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="section_assignments",
                to="tas.tastemplate",
            ),
        ),
        migrations.RemoveField(
            model_name="tastemplatesection",
            name="is_required",
        ),
        migrations.RemoveField(
            model_name="tastemplatesection",
            name="section_order",
        ),
        migrations.RemoveField(
            model_name="tastemplatesection",
            name="template",
        ),
        migrations.AddIndex(
            model_name="tastemplatesectionassignment",
            index=models.Index(
                fields=["template", "section_order"],
                name="tas_templat_templat_cc3cea_idx",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="tastemplatesectionassignment",
            unique_together={("template", "section")},
        ),
    ]
