# Generated by Django 5.1.13 on 2025-11-08 11:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tas', '0005_tastemplatesectionassignment_and_more'),
        ('tenants', '0003_tenantapikey_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TASConversionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=200)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing 2015 TAS'), ('mapping', 'Mapping to 2025 Standards'), ('converting', 'Converting Content'), ('validating', 'Validating Compliance'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0)),
                ('current_step', models.CharField(blank=True, max_length=200)),
                ('ai_model', models.CharField(default='gpt-4o', help_text='AI model used for conversion (gpt-4o, claude-3-opus, etc.)', max_length=50)),
                ('standards_mapping', models.JSONField(default=dict, help_text='Mapping from 2015 clauses to 2025 Quality Areas: {2015_clause: [2025_standards]}')),
                ('source_analysis', models.JSONField(default=dict, help_text='AI analysis of source TAS: sections identified, standards referenced, etc.')),
                ('conversion_changes', models.JSONField(default=list, help_text='List of changes made: [{section, old_content, new_content, rationale}]')),
                ('compliance_report', models.JSONField(default=dict, help_text='2025 Standards compliance check results')),
                ('sections_converted', models.IntegerField(default=0)),
                ('standards_updated', models.IntegerField(default=0)),
                ('quality_score', models.FloatField(blank=True, help_text='AI-assessed quality score of conversion (0-100)', null=True)),
                ('conversion_options', models.JSONField(default=dict, help_text='User preferences: {preserve_formatting, update_terminology, add_notes}')),
                ('processing_time_seconds', models.FloatField(default=0.0)),
                ('ai_tokens_used', models.IntegerField(default=0)),
                ('ai_cost_estimate', models.DecimalField(decimal_places=4, default=0, help_text='Estimated cost in USD', max_digits=10)),
                ('error_message', models.TextField(blank=True)),
                ('error_details', models.JSONField(default=dict)),
                ('requires_human_review', models.BooleanField(default=True, help_text='Flag sections that need human review')),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tas_conversions_created', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tas_conversions_reviewed', to=settings.AUTH_USER_MODEL)),
                ('source_tas', models.ForeignKey(help_text='Original TAS using 2015 Standards', on_delete=django.db.models.deletion.CASCADE, related_name='conversion_sessions_as_source', to='tas.tas')),
                ('target_tas', models.ForeignKey(blank=True, help_text='New TAS using 2025 Standards', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion_sessions_as_target', to='tas.tas')),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tas_conversion_sessions', to='tenants.tenant')),
            ],
            options={
                'verbose_name': 'TAS Conversion Session',
                'verbose_name_plural': 'TAS Conversion Sessions',
                'db_table': 'tas_conversion_sessions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['tenant', 'status'], name='tas_convers_tenant__7a098b_idx'), models.Index(fields=['source_tas'], name='tas_convers_source__969aca_idx'), models.Index(fields=['created_at'], name='tas_convers_created_389454_idx')],
            },
        ),
    ]
