# Generated by Django 5.1.2 on 2025-10-24 11:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrainerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "profile_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("tenant", models.CharField(db_index=True, max_length=100)),
                ("trainer_id", models.CharField(db_index=True, max_length=100)),
                ("trainer_name", models.CharField(max_length=200)),
                ("email", models.EmailField(blank=True, max_length=254)),
                ("linkedin_url", models.URLField(blank=True)),
                ("github_url", models.URLField(blank=True)),
                ("twitter_url", models.URLField(blank=True)),
                ("personal_website", models.URLField(blank=True)),
                ("primary_industry", models.CharField(blank=True, max_length=200)),
                ("specializations", models.JSONField(default=list)),
                ("years_experience", models.IntegerField(default=0)),
                ("last_verified_date", models.DateField(blank=True, null=True)),
                (
                    "currency_status",
                    models.CharField(
                        choices=[
                            ("current", "Current"),
                            ("expiring_soon", "Expiring Soon"),
                            ("expired", "Expired"),
                            ("not_verified", "Not Verified"),
                        ],
                        default="not_verified",
                        max_length=20,
                    ),
                ),
                ("currency_score", models.FloatField(default=0.0)),
                ("auto_verify_enabled", models.BooleanField(default=True)),
                ("verification_frequency_days", models.IntegerField(default=90)),
                ("next_verification_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-updated_at"],
                "indexes": [
                    models.Index(
                        fields=["tenant", "trainer_id"],
                        name="industry_cu_tenant_2d1abb_idx",
                    ),
                    models.Index(
                        fields=["currency_status", "-last_verified_date"],
                        name="industry_cu_currenc_82b72f_idx",
                    ),
                ],
                "unique_together": {("tenant", "trainer_id")},
            },
        ),
        migrations.CreateModel(
            name="VerificationScan",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "scan_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "scan_type",
                    models.CharField(
                        choices=[
                            ("manual", "Manual Scan"),
                            ("scheduled", "Scheduled Scan"),
                            ("automatic", "Automatic Scan"),
                        ],
                        default="manual",
                        max_length=20,
                    ),
                ),
                ("sources_to_scan", models.JSONField(default=list)),
                (
                    "scan_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("scanning", "Scanning"),
                            ("extracting", "Extracting Entities"),
                            ("analyzing", "Analyzing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("total_items_found", models.IntegerField(default=0)),
                ("relevant_items_count", models.IntegerField(default=0)),
                ("currency_score", models.FloatField(default=0.0)),
                ("scan_duration_seconds", models.FloatField(blank=True, null=True)),
                ("error_message", models.TextField(blank=True)),
                ("started_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trainer_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="scans",
                        to="industry_currency.trainerprofile",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LinkedInActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("post", "Post/Article"),
                            ("comment", "Comment"),
                            ("share", "Share"),
                            ("certification", "Certification"),
                            ("course", "Course Completion"),
                            ("project", "Project"),
                            ("position", "Work Position"),
                            ("skill_endorsement", "Skill Endorsement"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                ("activity_date", models.DateField(blank=True, null=True)),
                ("date_text", models.CharField(blank=True, max_length=200)),
                ("skills_mentioned", models.JSONField(default=list)),
                ("technologies", models.JSONField(default=list)),
                ("companies", models.JSONField(default=list)),
                ("keywords", models.JSONField(default=list)),
                ("relevance_score", models.FloatField(default=0.0)),
                ("is_industry_relevant", models.BooleanField(default=False)),
                ("relevance_reasoning", models.TextField(blank=True)),
                ("raw_data", models.JSONField(default=dict)),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "verification_scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="linkedin_activities",
                        to="industry_currency.verificationscan",
                    ),
                ),
            ],
            options={
                "ordering": ["-activity_date", "-extracted_at"],
            },
        ),
        migrations.CreateModel(
            name="GitHubActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "activity_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "activity_type",
                    models.CharField(
                        choices=[
                            ("repository", "Repository"),
                            ("commit", "Commit"),
                            ("pull_request", "Pull Request"),
                            ("issue", "Issue"),
                            ("contribution", "Contribution"),
                            ("gist", "Gist"),
                            ("star", "Star"),
                        ],
                        max_length=50,
                    ),
                ),
                ("repository_name", models.CharField(blank=True, max_length=300)),
                ("title", models.CharField(blank=True, max_length=500)),
                ("description", models.TextField(blank=True)),
                ("url", models.URLField(blank=True)),
                ("activity_date", models.DateField(blank=True, null=True)),
                ("last_updated", models.DateField(blank=True, null=True)),
                ("language", models.CharField(blank=True, max_length=100)),
                ("languages_used", models.JSONField(default=list)),
                ("topics", models.JSONField(default=list)),
                ("stars", models.IntegerField(default=0)),
                ("forks", models.IntegerField(default=0)),
                ("technologies", models.JSONField(default=list)),
                ("frameworks", models.JSONField(default=list)),
                ("keywords", models.JSONField(default=list)),
                ("relevance_score", models.FloatField(default=0.0)),
                ("is_industry_relevant", models.BooleanField(default=False)),
                ("relevance_reasoning", models.TextField(blank=True)),
                ("commits_count", models.IntegerField(default=0)),
                ("contributions_count", models.IntegerField(default=0)),
                ("raw_data", models.JSONField(default=dict)),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "verification_scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="github_activities",
                        to="industry_currency.verificationscan",
                    ),
                ),
            ],
            options={
                "ordering": ["-activity_date", "-extracted_at"],
            },
        ),
        migrations.CreateModel(
            name="EntityExtraction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "extraction_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("linkedin", "LinkedIn"),
                            ("github", "GitHub"),
                            ("twitter", "Twitter"),
                            ("website", "Website"),
                        ],
                        max_length=20,
                    ),
                ),
                ("source_url", models.URLField(blank=True)),
                ("source_text", models.TextField()),
                ("entities", models.JSONField(default=dict)),
                ("extraction_confidence", models.FloatField(default=0.0)),
                ("entity_count", models.IntegerField(default=0)),
                ("nlp_model_used", models.CharField(blank=True, max_length=100)),
                ("processing_time_ms", models.FloatField(blank=True, null=True)),
                ("extracted_at", models.DateTimeField(auto_now_add=True)),
                (
                    "verification_scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="entity_extractions",
                        to="industry_currency.verificationscan",
                    ),
                ),
            ],
            options={
                "ordering": ["-extracted_at"],
            },
        ),
        migrations.CreateModel(
            name="CurrencyEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "evidence_number",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("linkedin_summary", "LinkedIn Activity Summary"),
                            ("github_summary", "GitHub Activity Summary"),
                            ("combined_report", "Combined Currency Report"),
                            ("timeline", "Activity Timeline"),
                            ("skills_matrix", "Skills Matrix"),
                            ("currency_certificate", "Currency Certificate"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("content", models.TextField()),
                ("evidence_start_date", models.DateField(blank=True, null=True)),
                ("evidence_end_date", models.DateField(blank=True, null=True)),
                ("total_activities", models.IntegerField(default=0)),
                ("relevant_activities", models.IntegerField(default=0)),
                ("currency_score", models.FloatField(default=0.0)),
                ("linkedin_activities_included", models.JSONField(default=list)),
                ("github_activities_included", models.JSONField(default=list)),
                (
                    "file_format",
                    models.CharField(
                        choices=[
                            ("markdown", "Markdown"),
                            ("html", "HTML"),
                            ("pdf", "PDF"),
                            ("json", "JSON"),
                        ],
                        default="markdown",
                        max_length=20,
                    ),
                ),
                ("file_path", models.CharField(blank=True, max_length=1000)),
                ("file_size_kb", models.FloatField(blank=True, null=True)),
                ("meets_rto_standards", models.BooleanField(default=True)),
                ("compliance_notes", models.TextField(blank=True)),
                ("is_approved", models.BooleanField(default=False)),
                ("approved_by", models.CharField(blank=True, max_length=200)),
                ("approved_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "trainer_profile",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="currency_evidence",
                        to="industry_currency.trainerprofile",
                    ),
                ),
                (
                    "verification_scan",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_documents",
                        to="industry_currency.verificationscan",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddIndex(
            model_name="verificationscan",
            index=models.Index(
                fields=["trainer_profile", "-created_at"],
                name="industry_cu_trainer_0e0113_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="verificationscan",
            index=models.Index(
                fields=["scan_status", "-created_at"],
                name="industry_cu_scan_st_42b13a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="linkedinactivity",
            index=models.Index(
                fields=["verification_scan", "-activity_date"],
                name="industry_cu_verific_cb20d4_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="linkedinactivity",
            index=models.Index(
                fields=["is_industry_relevant", "-relevance_score"],
                name="industry_cu_is_indu_ed1608_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="githubactivity",
            index=models.Index(
                fields=["verification_scan", "-activity_date"],
                name="industry_cu_verific_9a6163_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="githubactivity",
            index=models.Index(
                fields=["is_industry_relevant", "-relevance_score"],
                name="industry_cu_is_indu_c46a24_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="entityextraction",
            index=models.Index(
                fields=["verification_scan", "source_type"],
                name="industry_cu_verific_84030c_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="currencyevidence",
            index=models.Index(
                fields=["trainer_profile", "-created_at"],
                name="industry_cu_trainer_11a39e_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="currencyevidence",
            index=models.Index(
                fields=["verification_scan", "-created_at"],
                name="industry_cu_verific_6166dc_idx",
            ),
        ),
    ]
