# Generated by Django 5.1.13 on 2025-11-08 11:11

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def preserve_existing_2015_standards(apps, schema_editor):
    """
    Data migration to preserve existing ASQAStandard records as 2015 version
    before changing the default to 2025 for new records.
    """
    ASQAStandard = apps.get_model('policy_comparator', 'ASQAStandard')
    # All existing records should remain as 2015 since that was the original default
    # This ensures we don't accidentally change existing 2015 standards to 2025
    ASQAStandard.objects.filter(version='2015').update(version='2015')


def reverse_preserve_2015_standards(apps, schema_editor):
    """
    Reverse data migration - no action needed as we're just preserving existing data.
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('policy_comparator', '0001_initial'),
        ('tenants', '0003_tenantapikey_description'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AsqaClausePack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('version', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'asqa_clause_packs',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=500)),
                ('source_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word Document'), ('html', 'HTML'), ('txt', 'Plain Text')], max_length=20)),
                ('s3_uri', models.CharField(help_text='S3 path to original file', max_length=1000)),
                ('sha256', models.CharField(db_index=True, help_text='File hash for deduplication', max_length=64)),
                ('language', models.CharField(default='en', max_length=10)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('word_count', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending Upload'), ('uploading', 'Uploading'), ('processing', 'Processing'), ('ready', 'Ready'), ('failed', 'Failed'), ('archived', 'Archived')], default='pending', max_length=20)),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'policy_documents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='DocumentChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_idx', models.IntegerField(help_text='Sequential index of chunk')),
                ('text', models.TextField()),
                ('tokens', models.IntegerField(help_text='Token count for this chunk')),
                ('section_path', models.CharField(blank=True, help_text="Heading path, e.g., '1. Introduction > 1.1 Purpose'", max_length=500)),
                ('page_from', models.IntegerField(blank=True, null=True)),
                ('page_to', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'document_chunks',
                'ordering': ['document_version', 'chunk_idx'],
            },
        ),
        migrations.CreateModel(
            name='DocumentVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_no', models.IntegerField()),
                ('s3_uri', models.CharField(max_length=1000)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'document_versions',
                'ordering': ['-version_no'],
            },
        ),
        migrations.CreateModel(
            name='PolicyConversionSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_name', models.CharField(max_length=300)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('analyzing', 'Analyzing Source Policy'), ('mapping', 'Mapping Standards'), ('converting', 'Converting Content'), ('validating', 'Validating Compliance'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('progress_percentage', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('ai_model', models.CharField(default='gpt-4o', help_text='AI model used for conversion (gpt-4o, claude-3-opus, etc.)', max_length=50)),
                ('standards_mapping', models.JSONField(default=dict, help_text='Detailed mapping from 2015 to 2025 standards for this policy')),
                ('conversion_changes', models.JSONField(default=list, help_text='List of all changes made during conversion')),
                ('compliance_report', models.JSONField(default=dict, help_text='Compliance validation report against 2025 Standards')),
                ('source_analysis', models.JSONField(default=dict, help_text='Analysis of source policy structure and standards references')),
                ('quality_score', models.FloatField(blank=True, help_text='AI-assessed quality of conversion (0-100)', null=True, validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(100.0)])),
                ('requires_human_review', models.BooleanField(default=False, help_text='Flags if conversion requires human review before approval')),
                ('processing_time_seconds', models.FloatField(default=0.0)),
                ('ai_tokens_used', models.IntegerField(default=0, help_text='Total AI tokens consumed')),
                ('error_message', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Policy Conversion Session',
                'verbose_name_plural': 'Policy Conversion Sessions',
                'db_table': 'policy_conversion_sessions',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='asqastandard',
            options={'ordering': ['version', 'quality_area', 'standard_number'], 'verbose_name': 'ASQA Standard', 'verbose_name_plural': 'ASQA Standards'},
        ),
        migrations.AddField(
            model_name='asqastandard',
            name='asqa_url',
            field=models.URLField(blank=True, help_text='Link to official ASQA documentation', max_length=500),
        ),
        migrations.AddField(
            model_name='asqastandard',
            name='quality_area',
            field=models.IntegerField(blank=True, help_text='Quality Area number (1-4) for 2025 Outcome Standards', null=True),
        ),
        migrations.AddField(
            model_name='asqastandard',
            name='standard_category',
            field=models.CharField(choices=[('outcome', 'Outcome Standard'), ('compliance', 'Compliance Requirement'), ('credential', 'Credential Policy'), ('legacy_2015', '2015 Standard')], default='legacy_2015', help_text='Classification within 2025 standards framework', max_length=20),
        ),
        migrations.AlterField(
            model_name='asqastandard',
            name='standard_number',
            field=models.CharField(db_index=True, help_text='e.g., Standard 1.1 (2015) or QA1.1 (2025)', max_length=20),
        ),
        migrations.AlterField(
            model_name='asqastandard',
            name='standard_type',
            field=models.CharField(choices=[('training_assessment', 'Training and Assessment'), ('trainer_assessor', 'Trainer and Assessor'), ('educational_support', 'Educational and Support Services'), ('certification', 'Certification'), ('engagement_employer', 'Engagement with Employers'), ('complaints_appeals', 'Complaints and Appeals'), ('governance', 'Governance and Administration'), ('financial', 'Financial Management'), ('qa1_training_assessment', 'Quality Area 1 - Training and Assessment'), ('qa2_student_support', 'Quality Area 2 - VET Student Support'), ('qa3_workforce', 'Quality Area 3 - VET Workforce'), ('qa4_governance', 'Quality Area 4 - Governance'), ('compliance_information', 'Compliance - Information and Transparency'), ('compliance_integrity', 'Compliance - Integrity of NRT Products'), ('compliance_accountability', 'Compliance - Accountability'), ('compliance_fit_proper', 'Compliance - Fit and Proper Person'), ('credential_policy', 'Credential Policy')], max_length=50),
        ),
        # Data migration to preserve existing 2015 standards before changing default to 2025
        migrations.RunPython(preserve_existing_2015_standards, reverse_preserve_2015_standards),
        migrations.AlterField(
            model_name='asqastandard',
            name='version',
            field=models.CharField(choices=[('2015', 'Standards for RTOs 2015'), ('2025', 'Standards for RTOs 2025')], default='2025', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='asqastandard',
            unique_together={('standard_number', 'version')},
        ),
        migrations.AddIndex(
            model_name='asqastandard',
            index=models.Index(fields=['version', 'is_active'], name='asqa_standa_version_96c685_idx'),
        ),
        migrations.AddIndex(
            model_name='asqastandard',
            index=models.Index(fields=['standard_category'], name='asqa_standa_standar_de1c1d_idx'),
        ),
        migrations.AddIndex(
            model_name='asqastandard',
            index=models.Index(fields=['quality_area'], name='asqa_standa_quality_7fc30d_idx'),
        ),
        migrations.AddField(
            model_name='asqaclausepack',
            name='tenant',
            field=models.ForeignKey(blank=True, help_text='Null for global ASQA packs', null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='document',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_documents', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='document',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_documents', to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='documentversion',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='policy_comparator.document'),
        ),
        migrations.AddField(
            model_name='documentchunk',
            name='document_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='policy_comparator.documentversion'),
        ),
        migrations.AddField(
            model_name='policyconversionsession',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='policy_conversions_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='policyconversionsession',
            name='source_policy',
            field=models.ForeignKey(help_text='Original policy based on 2015 Standards', on_delete=django.db.models.deletion.CASCADE, related_name='conversion_sessions_as_source', to='policy_comparator.policy'),
        ),
        migrations.AddField(
            model_name='policyconversionsession',
            name='target_policy',
            field=models.ForeignKey(blank=True, help_text='New policy based on 2025 Standards', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='conversion_sessions_as_target', to='policy_comparator.policy'),
        ),
        migrations.AddField(
            model_name='policyconversionsession',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_conversion_sessions', to='tenants.tenant'),
        ),
        migrations.AlterUniqueTogether(
            name='asqaclausepack',
            unique_together={('tenant', 'name', 'version')},
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['tenant', 'status'], name='policy_docu_tenant__b7d5be_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['sha256'], name='policy_docu_sha256_0c4914_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='documentversion',
            unique_together={('document', 'version_no')},
        ),
        migrations.AddIndex(
            model_name='documentchunk',
            index=models.Index(fields=['document_version', 'chunk_idx'], name='document_ch_documen_5b34d1_idx'),
        ),
        migrations.AddIndex(
            model_name='policyconversionsession',
            index=models.Index(fields=['tenant', 'status'], name='policy_conv_tenant__1c5eee_idx'),
        ),
        migrations.AddIndex(
            model_name='policyconversionsession',
            index=models.Index(fields=['source_policy'], name='policy_conv_source__b16b4c_idx'),
        ),
        migrations.AddIndex(
            model_name='policyconversionsession',
            index=models.Index(fields=['status', 'created_at'], name='policy_conv_status_30ec49_idx'),
        ),
    ]
