# Generated by Django 5.1.2 on 2025-10-24 04:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="RiskAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "assessment_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("student_id", models.CharField(max_length=100)),
                ("student_name", models.CharField(max_length=255)),
                (
                    "dropout_probability",
                    models.FloatField(
                        help_text="Predicted dropout probability (0.0 - 1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "risk_level",
                    models.CharField(
                        choices=[
                            ("low", "Low Risk"),
                            ("medium", "Medium Risk"),
                            ("high", "High Risk"),
                            ("critical", "Critical Risk"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "risk_score",
                    models.IntegerField(
                        help_text="Overall risk score (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                (
                    "engagement_score",
                    models.FloatField(
                        help_text="Engagement level score",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "performance_score",
                    models.FloatField(
                        help_text="Academic performance score",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "attendance_score",
                    models.FloatField(
                        help_text="Attendance rate score",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "sentiment_score",
                    models.FloatField(
                        help_text="Sentiment analysis score (-1.0 to 1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(-1.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "model_version",
                    models.CharField(default="logistic_v1.0", max_length=50),
                ),
                (
                    "confidence",
                    models.FloatField(
                        help_text="Model confidence percentage",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("active", "Active"),
                            ("monitoring", "Monitoring"),
                            ("intervention_required", "Intervention Required"),
                            ("resolved", "Resolved"),
                            ("dropped_out", "Dropped Out"),
                        ],
                        default="active",
                        max_length=30,
                    ),
                ),
                ("assessment_date", models.DateField(auto_now_add=True)),
                ("last_updated", models.DateTimeField(auto_now=True)),
                ("alert_triggered", models.BooleanField(default=False)),
                ("alert_acknowledged", models.BooleanField(default=False)),
                ("alert_acknowledged_at", models.DateTimeField(blank=True, null=True)),
                ("intervention_assigned", models.BooleanField(default=False)),
                ("intervention_notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "alert_acknowledged_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="acknowledged_alerts",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-assessment_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="InterventionAction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "action_type",
                    models.CharField(
                        choices=[
                            ("email_outreach", "Email Outreach"),
                            ("phone_call", "Phone Call"),
                            ("meeting_scheduled", "Meeting Scheduled"),
                            ("counseling_referral", "Counseling Referral"),
                            ("academic_support", "Academic Support"),
                            ("mentoring", "Mentoring Assignment"),
                            ("course_adjustment", "Course Adjustment"),
                            ("financial_support", "Financial Support Referral"),
                        ],
                        max_length=30,
                    ),
                ),
                ("description", models.TextField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                ("scheduled_date", models.DateField(blank=True, null=True)),
                ("completed_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("outcome_notes", models.TextField(blank=True)),
                (
                    "effectiveness_rating",
                    models.IntegerField(
                        blank=True,
                        help_text="Effectiveness rating (1-5)",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_interventions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="created_interventions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="interventions",
                        to="risk_engine.riskassessment",
                    ),
                ),
            ],
            options={
                "ordering": ["-scheduled_date", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RiskFactor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "factor_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "factor_type",
                    models.CharField(
                        choices=[
                            ("academic", "Academic Performance"),
                            ("attendance", "Attendance"),
                            ("engagement", "Engagement"),
                            ("behavioral", "Behavioral"),
                            ("socioeconomic", "Socioeconomic"),
                            ("personal", "Personal Circumstances"),
                            ("sentiment", "Sentiment Analysis"),
                        ],
                        max_length=20,
                    ),
                ),
                ("factor_name", models.CharField(max_length=255)),
                ("description", models.TextField()),
                (
                    "weight",
                    models.FloatField(
                        help_text="Factor weight in model (0.0 - 1.0)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "contribution",
                    models.FloatField(
                        help_text="Contribution to overall risk (%)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("critical", "Critical"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "current_value",
                    models.FloatField(help_text="Current measured value"),
                ),
                (
                    "threshold_value",
                    models.FloatField(help_text="Risk threshold value"),
                ),
                ("threshold_exceeded", models.BooleanField(default=False)),
                (
                    "trend",
                    models.CharField(
                        choices=[
                            ("improving", "Improving"),
                            ("stable", "Stable"),
                            ("declining", "Declining"),
                            ("critical_decline", "Critical Decline"),
                        ],
                        default="stable",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="risk_factors",
                        to="risk_engine.riskassessment",
                    ),
                ),
            ],
            options={
                "ordering": ["-contribution", "-weight"],
            },
        ),
        migrations.CreateModel(
            name="SentimentAnalysis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "analysis_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("email", "Email"),
                            ("forum_post", "Forum Post"),
                            ("chat", "Chat Message"),
                            ("feedback", "Feedback Form"),
                            ("survey", "Survey Response"),
                        ],
                        max_length=50,
                    ),
                ),
                ("text_sample", models.TextField(help_text="Sample text analyzed")),
                (
                    "sentiment_score",
                    models.FloatField(
                        help_text="Sentiment score (-1.0 = very negative, 1.0 = very positive)",
                        validators=[
                            django.core.validators.MinValueValidator(-1.0),
                            django.core.validators.MaxValueValidator(1.0),
                        ],
                    ),
                ),
                (
                    "sentiment_label",
                    models.CharField(
                        choices=[
                            ("very_negative", "Very Negative"),
                            ("negative", "Negative"),
                            ("neutral", "Neutral"),
                            ("positive", "Positive"),
                            ("very_positive", "Very Positive"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "confidence",
                    models.FloatField(
                        help_text="Sentiment model confidence",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("frustration_detected", models.BooleanField(default=False)),
                ("stress_detected", models.BooleanField(default=False)),
                ("confusion_detected", models.BooleanField(default=False)),
                ("disengagement_detected", models.BooleanField(default=False)),
                ("negative_keywords", models.JSONField(blank=True, default=list)),
                ("risk_indicators", models.JSONField(blank=True, default=list)),
                ("analysis_date", models.DateTimeField(auto_now_add=True)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sentiment_analyses",
                        to="risk_engine.riskassessment",
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Sentiment analyses",
                "ordering": ["-analysis_date"],
            },
        ),
        migrations.CreateModel(
            name="StudentEngagementMetric",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "metric_number",
                    models.CharField(editable=False, max_length=50, unique=True),
                ),
                ("student_id", models.CharField(db_index=True, max_length=100)),
                ("student_name", models.CharField(max_length=255)),
                ("login_frequency", models.IntegerField(help_text="Logins per week")),
                ("time_on_platform", models.FloatField(help_text="Hours per week")),
                (
                    "assignment_submission_rate",
                    models.FloatField(
                        help_text="Assignment submission rate (%)",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                (
                    "forum_participation",
                    models.IntegerField(help_text="Forum posts/comments count"),
                ),
                (
                    "peer_interaction_score",
                    models.FloatField(
                        help_text="Peer interaction score",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("last_login", models.DateTimeField(blank=True, null=True)),
                ("days_inactive", models.IntegerField(default=0)),
                (
                    "activity_decline_rate",
                    models.FloatField(
                        default=0.0, help_text="Week-over-week decline %"
                    ),
                ),
                (
                    "overall_engagement_score",
                    models.FloatField(
                        help_text="Composite engagement score",
                        validators=[
                            django.core.validators.MinValueValidator(0.0),
                            django.core.validators.MaxValueValidator(100.0),
                        ],
                    ),
                ),
                ("measurement_date", models.DateField(auto_now_add=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["-measurement_date"],
                "indexes": [
                    models.Index(
                        fields=["student_id", "-measurement_date"],
                        name="risk_engine_student_e1282a_idx",
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="riskassessment",
            index=models.Index(
                fields=["student_id", "-assessment_date"],
                name="risk_engine_student_0361e3_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="riskassessment",
            index=models.Index(
                fields=["risk_level", "status"], name="risk_engine_risk_le_685250_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="riskassessment",
            index=models.Index(
                fields=["alert_triggered", "alert_acknowledged"],
                name="risk_engine_alert_t_136255_idx",
            ),
        ),
    ]
