# Generated by Django 5.1.2 on 2025-10-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("audit", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="audit",
            name="timestamp",
            field=models.DateTimeField(),
        ),
    ]
