# Generated by Django 5.1.2 on 2025-11-01 22:28

import funding_eligibility.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("funding_eligibility", "0003_alter_jurisdictionrequirement_effective_from"),
    ]

    operations = [
        migrations.AlterField(
            model_name="jurisdictionrequirement",
            name="effective_from",
            field=models.DateField(default=funding_eligibility.models.get_current_date),
        ),
    ]
