# Generated by Django 5.1.2 on 2025-10-24 02:21

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rubric_generator', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('tenant', models.CharField(db_index=True, max_length=100)),
                ('feedback_type', models.CharField(choices=[('formative', 'Formative'), ('summative', 'Summative'), ('diagnostic', 'Diagnostic'), ('peer', 'Peer Review'), ('self_assessment', 'Self-Assessment')], default='formative', max_length=50)),
                ('sentiment', models.CharField(choices=[('encouraging', 'Encouraging'), ('constructive', 'Constructive'), ('neutral', 'Neutral'), ('direct', 'Direct'), ('motivational', 'Motivational')], default='constructive', max_length=50)),
                ('tone', models.CharField(choices=[('formal', 'Formal'), ('conversational', 'Conversational'), ('supportive', 'Supportive'), ('professional', 'Professional'), ('friendly', 'Friendly')], default='professional', max_length=50)),
                ('maps_to_criteria', models.JSONField(blank=True, default=list, help_text='List of rubric criterion IDs')),
                ('include_student_name', models.BooleanField(default=True)),
                ('include_strengths', models.BooleanField(default=True)),
                ('include_improvements', models.BooleanField(default=True)),
                ('include_next_steps', models.BooleanField(default=True)),
                ('include_encouragement', models.BooleanField(default=True)),
                ('opening_template', models.TextField(default='Dear {student_name},', help_text='Opening statement template')),
                ('strengths_template', models.TextField(blank=True, default='Your strengths include: {strengths}')),
                ('improvements_template', models.TextField(blank=True, default='Areas for improvement: {improvements}')),
                ('next_steps_template', models.TextField(blank=True, default='Next steps: {next_steps}')),
                ('closing_template', models.TextField(blank=True, default='Keep up the great work!')),
                ('positivity_level', models.IntegerField(default=7, help_text='1=Very Critical, 10=Very Positive', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('directness_level', models.IntegerField(default=5, help_text='1=Very Indirect, 10=Very Direct', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('formality_level', models.IntegerField(default=7, help_text='1=Very Casual, 10=Very Formal', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(10)])),
                ('total_feedback_generated', models.IntegerField(default=0)),
                ('average_generation_time', models.FloatField(default=0.0, help_text='Average time in seconds')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_templates', to=settings.AUTH_USER_MODEL)),
                ('rubric', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rubric_generator.rubric')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackCriterion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('criterion_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('excellent_feedback', models.TextField(help_text='Feedback for excellent performance')),
                ('good_feedback', models.TextField(help_text='Feedback for good performance')),
                ('satisfactory_feedback', models.TextField(help_text='Feedback for satisfactory performance')),
                ('needs_improvement_feedback', models.TextField(help_text='Feedback for needs improvement')),
                ('weight', models.FloatField(default=1.0, help_text='Importance of this criterion', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('display_order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('rubric_criterion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rubric_generator.rubriccriterion')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='criteria', to='feedback_assistant.feedbacktemplate')),
            ],
            options={
                'verbose_name_plural': 'Feedback Criteria',
                'ordering': ['display_order', 'created_at'],
            },
        ),
        migrations.CreateModel(
            name='GeneratedFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feedback_number', models.CharField(editable=False, max_length=50, unique=True)),
                ('student_id', models.CharField(db_index=True, max_length=100)),
                ('student_name', models.CharField(max_length=255)),
                ('assessment_title', models.CharField(blank=True, max_length=255)),
                ('score', models.FloatField(blank=True, null=True)),
                ('max_score', models.FloatField(blank=True, null=True)),
                ('grade', models.CharField(blank=True, max_length=10)),
                ('rubric_scores', models.JSONField(blank=True, default=dict, help_text='Scores per rubric criterion')),
                ('feedback_text', models.TextField()),
                ('strengths_identified', models.JSONField(blank=True, default=list)),
                ('improvements_identified', models.JSONField(blank=True, default=list)),
                ('next_steps_suggested', models.JSONField(blank=True, default=list)),
                ('sentiment_score', models.FloatField(default=0.0, help_text='Sentiment: -1 (negative) to +1 (positive)', validators=[django.core.validators.MinValueValidator(-1.0), django.core.validators.MaxValueValidator(1.0)])),
                ('tone_consistency', models.FloatField(default=1.0, help_text='How well tone matches template settings', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('word_count', models.IntegerField(default=0)),
                ('reading_level', models.CharField(blank=True, help_text='e.g., Grade 10, University', max_length=50)),
                ('personalization_score', models.FloatField(default=0.0, help_text='How personalized the feedback is', validators=[django.core.validators.MinValueValidator(0.0), django.core.validators.MaxValueValidator(1.0)])),
                ('requires_review', models.BooleanField(db_index=True, default=False)),
                ('review_notes', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('delivered_at', models.DateTimeField(blank=True, null=True)),
                ('delivery_method', models.CharField(blank=True, help_text='email, LMS, portal, etc.', max_length=50)),
                ('status', models.CharField(choices=[('generating', 'Generating'), ('generated', 'Generated'), ('reviewed', 'Reviewed'), ('delivered', 'Delivered'), ('revised', 'Revised')], db_index=True, default='generating', max_length=20)),
                ('generation_time', models.FloatField(default=0.0, help_text='Time to generate in seconds')),
                ('generated_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_feedbacks', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='generated_feedbacks', to='feedback_assistant.feedbacktemplate')),
            ],
            options={
                'ordering': ['-generated_at'],
            },
        ),
        migrations.CreateModel(
            name='FeedbackLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('generate_single', 'Generate Single'), ('generate_batch', 'Generate Batch'), ('review', 'Review Feedback'), ('revise', 'Revise Feedback'), ('deliver', 'Deliver Feedback'), ('template_update', 'Update Template')], db_index=True, max_length=50)),
                ('feedbacks_generated', models.IntegerField(default=1)),
                ('total_time', models.FloatField(help_text='Total processing time in seconds')),
                ('average_time_per_feedback', models.FloatField(default=0.0)),
                ('average_sentiment', models.FloatField(blank=True, null=True)),
                ('average_personalization', models.FloatField(blank=True, null=True)),
                ('changes_made', models.TextField(blank=True)),
                ('previous_version', models.TextField(blank=True)),
                ('details', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='feedback_assistant.feedbacktemplate')),
                ('feedback', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='feedback_assistant.generatedfeedback')),
            ],
            options={
                'ordering': ['-timestamp'],
            },
        ),
        migrations.AddIndex(
            model_name='feedbacktemplate',
            index=models.Index(fields=['tenant', 'status'], name='feedback_as_tenant_7c84e7_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacktemplate',
            index=models.Index(fields=['feedback_type'], name='feedback_as_feedbac_099d5f_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacktemplate',
            index=models.Index(fields=['created_at'], name='feedback_as_created_c1a35d_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedfeedback',
            index=models.Index(fields=['template', 'status'], name='feedback_as_templat_7d8b02_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedfeedback',
            index=models.Index(fields=['student_id'], name='feedback_as_student_e2ae18_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedfeedback',
            index=models.Index(fields=['requires_review'], name='feedback_as_require_c73674_idx'),
        ),
        migrations.AddIndex(
            model_name='generatedfeedback',
            index=models.Index(fields=['generated_at'], name='feedback_as_generat_fb6a2e_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacklog',
            index=models.Index(fields=['template', 'action'], name='feedback_as_templat_4851a5_idx'),
        ),
        migrations.AddIndex(
            model_name='feedbacklog',
            index=models.Index(fields=['timestamp'], name='feedback_as_timesta_c0fafb_idx'),
        ),
    ]
