# Generated by Django 5.1.2 on 2025-10-24 00:36

import audit_assistant.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("policy_comparator", "0001_initial"),
        ("tenants", "0003_tenantapikey_description"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditReport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("report_number", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "audit_period_start",
                    models.DateField(help_text="Start date of audit period"),
                ),
                (
                    "audit_period_end",
                    models.DateField(help_text="End date of audit period"),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("in_progress", "In Progress"),
                            ("review", "Under Review"),
                            ("completed", "Completed"),
                            ("submitted", "Submitted to ASQA"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("total_clauses", models.IntegerField(default=0)),
                ("clauses_with_evidence", models.IntegerField(default=0)),
                ("clauses_without_evidence", models.IntegerField(default=0)),
                (
                    "compliance_percentage",
                    models.FloatField(
                        default=0.0, help_text="Percentage of clauses with evidence"
                    ),
                ),
                ("critical_clauses_count", models.IntegerField(default=0)),
                ("critical_clauses_covered", models.IntegerField(default=0)),
                ("critical_compliance_percentage", models.FloatField(default=0.0)),
                ("total_evidence_count", models.IntegerField(default=0)),
                (
                    "auto_tagged_count",
                    models.IntegerField(
                        default=0, help_text="Evidence auto-tagged via NER"
                    ),
                ),
                ("manually_tagged_count", models.IntegerField(default=0)),
                ("verified_evidence_count", models.IntegerField(default=0)),
                (
                    "findings",
                    models.JSONField(
                        default=list,
                        help_text="List of findings: [{clause: str, finding: str, severity: str, recommendation: str}]",
                    ),
                ),
                (
                    "recommendations",
                    models.JSONField(default=list, help_text="Overall recommendations"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("submitted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "asqa_standards",
                    models.ManyToManyField(
                        help_text="ASQA standards included in this audit",
                        related_name="audit_reports",
                        to="policy_comparator.asqastandard",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_audit_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "submitted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="submitted_audit_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="audit_reports",
                        to="tenants.tenant",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Report",
                "verbose_name_plural": "Audit Reports",
                "db_table": "audit_reports",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ClauseEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "mapping_type",
                    models.CharField(
                        choices=[
                            ("auto_ner", "Auto-tagged (NER)"),
                            ("auto_rule", "Auto-tagged (Rule-based)"),
                            ("manual", "Manual Assignment"),
                            ("suggested", "Suggested Match"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "confidence_score",
                    models.FloatField(
                        default=0.0,
                        help_text="Confidence score (0.0-1.0) for auto-tagged matches",
                    ),
                ),
                (
                    "matched_entities",
                    models.JSONField(
                        default=list,
                        help_text="NER entities that triggered this mapping: [{entity: str, type: str}]",
                    ),
                ),
                (
                    "matched_keywords",
                    models.JSONField(
                        default=list,
                        help_text="Keywords that matched between clause and evidence",
                    ),
                ),
                (
                    "rule_name",
                    models.CharField(
                        blank=True,
                        help_text="Name of rule that triggered mapping",
                        max_length=100,
                    ),
                ),
                (
                    "rule_metadata",
                    models.JSONField(
                        default=dict, help_text="Additional rule processing data"
                    ),
                ),
                (
                    "is_verified",
                    models.BooleanField(
                        default=False, help_text="Manually verified by reviewer"
                    ),
                ),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                (
                    "relevance_notes",
                    models.TextField(
                        blank=True, help_text="Notes on evidence relevance to clause"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asqa_clause",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="policy_comparator.asqaclause",
                    ),
                ),
                (
                    "verified_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Clause Evidence Mapping",
                "verbose_name_plural": "Clause Evidence Mappings",
                "db_table": "clause_evidence",
                "ordering": ["-confidence_score", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Evidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("evidence_number", models.CharField(max_length=50)),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True)),
                (
                    "evidence_type",
                    models.CharField(
                        choices=[
                            ("policy", "Policy Document"),
                            ("procedure", "Procedure"),
                            ("record", "Record/Log"),
                            ("template", "Template/Form"),
                            ("certificate", "Certificate"),
                            ("qualification", "Qualification Document"),
                            ("training_material", "Training Material"),
                            ("assessment", "Assessment Document"),
                            ("quality_assurance", "Quality Assurance Document"),
                            ("financial", "Financial Document"),
                            ("contract", "Contract/Agreement"),
                            ("correspondence", "Correspondence"),
                            ("meeting_minutes", "Meeting Minutes"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        help_text="Supported formats: PDF, Word, Excel, Text, Images",
                        upload_to=audit_assistant.models.evidence_upload_path,
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                allowed_extensions=[
                                    "pdf",
                                    "docx",
                                    "doc",
                                    "xlsx",
                                    "xls",
                                    "txt",
                                    "jpg",
                                    "jpeg",
                                    "png",
                                ]
                            )
                        ],
                    ),
                ),
                (
                    "file_size",
                    models.IntegerField(
                        blank=True, help_text="File size in bytes", null=True
                    ),
                ),
                (
                    "extracted_text",
                    models.TextField(
                        blank=True, help_text="Text extracted from uploaded file"
                    ),
                ),
                (
                    "ner_entities",
                    models.JSONField(
                        default=list,
                        help_text="Named entities extracted: {entity: str, type: str, start: int, end: int}",
                    ),
                ),
                ("ner_processed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("uploaded", "Uploaded"),
                            ("processing", "Processing NER"),
                            ("tagged", "Auto-Tagged"),
                            ("reviewed", "Reviewed"),
                            ("approved", "Approved"),
                            ("rejected", "Rejected"),
                        ],
                        default="uploaded",
                        max_length=20,
                    ),
                ),
                (
                    "tags",
                    models.JSONField(
                        default=list, help_text="Custom tags for categorization"
                    ),
                ),
                (
                    "evidence_date",
                    models.DateField(help_text="Date the evidence was created/issued"),
                ),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("reviewer_notes", models.TextField(blank=True)),
                (
                    "auto_tagged_clauses",
                    models.ManyToManyField(
                        help_text="ASQA clauses automatically tagged via NER",
                        related_name="evidence_documents",
                        through="audit_assistant.ClauseEvidence",
                        to="policy_comparator.asqaclause",
                    ),
                ),
                (
                    "reviewed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reviewed_evidence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tenant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="evidence_documents",
                        to="tenants.tenant",
                    ),
                ),
                (
                    "uploaded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="uploaded_evidence",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Evidence Document",
                "verbose_name_plural": "Evidence Documents",
                "db_table": "evidence",
                "ordering": ["-uploaded_at"],
            },
        ),
        migrations.AddField(
            model_name="clauseevidence",
            name="evidence",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="audit_assistant.evidence",
            ),
        ),
        migrations.CreateModel(
            name="AuditReportClause",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "compliance_status",
                    models.CharField(
                        choices=[
                            ("compliant", "Compliant"),
                            ("partial", "Partially Compliant"),
                            ("non_compliant", "Non-Compliant"),
                            ("not_assessed", "Not Assessed"),
                        ],
                        default="not_assessed",
                        max_length=20,
                    ),
                ),
                ("evidence_count", models.IntegerField(default=0)),
                ("verified_evidence_count", models.IntegerField(default=0)),
                (
                    "finding",
                    models.TextField(
                        blank=True, help_text="Audit finding for this clause"
                    ),
                ),
                (
                    "severity",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("critical", "Critical"),
                            ("major", "Major"),
                            ("minor", "Minor"),
                            ("observation", "Observation"),
                        ],
                        max_length=20,
                    ),
                ),
                ("recommendation", models.TextField(blank=True)),
                ("assessed_at", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "asqa_clause",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="policy_comparator.asqaclause",
                    ),
                ),
                (
                    "assessed_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "audit_report",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="clause_entries",
                        to="audit_assistant.auditreport",
                    ),
                ),
                (
                    "linked_evidence",
                    models.ManyToManyField(
                        blank=True,
                        related_name="audit_clause_entries",
                        to="audit_assistant.evidence",
                    ),
                ),
            ],
            options={
                "verbose_name": "Audit Report Clause",
                "verbose_name_plural": "Audit Report Clauses",
                "db_table": "audit_report_clauses",
                "ordering": ["asqa_clause__clause_number"],
            },
        ),
        migrations.AddIndex(
            model_name="auditreport",
            index=models.Index(
                fields=["tenant", "status"], name="audit_repor_tenant__f51757_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditreport",
            index=models.Index(
                fields=["audit_period_start", "audit_period_end"],
                name="audit_repor_audit_p_0e3007_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="auditreport",
            index=models.Index(
                fields=["compliance_percentage"], name="audit_repor_complia_a403fc_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="auditreport",
            unique_together={("tenant", "report_number")},
        ),
        migrations.AddIndex(
            model_name="evidence",
            index=models.Index(
                fields=["tenant", "status"], name="evidence_tenant__67f987_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evidence",
            index=models.Index(
                fields=["evidence_type"], name="evidence_evidenc_a2d96a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="evidence",
            index=models.Index(
                fields=["evidence_date"], name="evidence_evidenc_aa6bd4_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="evidence",
            unique_together={("tenant", "evidence_number")},
        ),
        migrations.AddIndex(
            model_name="clauseevidence",
            index=models.Index(
                fields=["mapping_type"], name="clause_evid_mapping_c1b719_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clauseevidence",
            index=models.Index(
                fields=["confidence_score"], name="clause_evid_confide_39f0d9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="clauseevidence",
            index=models.Index(
                fields=["is_verified"], name="clause_evid_is_veri_90c4f6_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="clauseevidence",
            unique_together={("asqa_clause", "evidence")},
        ),
        migrations.AddIndex(
            model_name="auditreportclause",
            index=models.Index(
                fields=["compliance_status"], name="audit_repor_complia_0d7377_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="auditreportclause",
            index=models.Index(
                fields=["severity"], name="audit_repor_severit_0bf062_idx"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="auditreportclause",
            unique_together={("audit_report", "asqa_clause")},
        ),
    ]
